config/routes.rb
Rails.application.routes.draw do

  get "/admin" => "clearance/sessions#new", as: "sign_in"
  delete "/sign-out" => "clearance/sessions#destroy", as: "sign_out"
  resource :session, controller: "clearance/sessions", only: [:create]

  root 'static#home'
  get '/work', to: 'static#work', as: :work
  get '/work/:id', to: 'static#show', as: :show_work
  get '/about', to: 'static#about', as: :about
  get '/contact', to: 'static#contact', as: :contact
  post '/contact', to: 'static#send_message', as: :send_message

  resources :projects, except: :show

end

app/models/contact_form.rb
class ContactForm < MailForm::Base
  attributes :first_name, :validate => true
  attributes :last_name, :validate => true
  attributes :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attributes :message

  def headers
    {
      :subject => "edenhibbert.com contact form",
      :to => "edenhibbert@gmail.com",
      :from => %("#{first_name}" <#{email}>)
    }
  end
end

app/models/image.rb
class Image < ActiveRecord::Base

  belongs_to :project

  has_attached_file :file, styles: {
    slider: "1280x400#",
    grid: "450x280",
    thumb: "200x200#" },
    default_url: 'missing.png'
  validates_attachment_content_type :file, content_type: /\Aimage\/.*\Z/


  private

  def create_default_url
     ActionController::Base.helpers.asset_path("/missing/:style.png", :digest => false)
  end

end

app/models/project.rb
class Project < ActiveRecord::Base

  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, reject_if: :all_blank, allow_destroy: true

  validates_presence_of :name, :date, :details

end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :require_login

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
    @project.images.build
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path, notice: 'Project created.'
    else
      render :new
    end
  end

  def edit
    @project = Project.friendly.find(params[:id])
  end

  def update
    @project = Project.friendly.find(params[:id])
    if @project.update_attributes(project_params)
      redirect_to projects_path, notice: 'Project updated.'
    else
      render :edit
    end
  end

  def destroy
    @project = Project.friendly.find(params[:id])
    if @project.destroy
      redirect_to projects_path, notice: "Project deleted."
    else
      redirect_to projects_path, notice: "Project could not be deleted."
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :date, :details, :image, images_attributes: [:id, :file, :featured, :_destroy] )
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def home
    @slides = Image.where(featured: true)
  end

  def work
    @projects = Project.all
  end

  def show
    @project = Project.friendly.find(params[:id])
  end

  def about
  end

  def contact
  end

  def send_message
    contact_message = ContactForm.new(contact_params)
    if contact_message.valid?
      contact_message.deliver
      redirect_to root_path, notice: "Your message was successfully sent!"
    else
      render :contact, notice: "Your message was not able to be sent, please try again later"
    end
  end

  private

  def contact_params
    params.permit(:first_name, :last_name, :email, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper

  def nav_link(name, path)
    haml_tag :li, class: "waves-effect waves-nav #{'active' if current_page?(path)}" do
      haml_tag :a, name.titleize, href: path
    end
  end

end

app/views/layouts/_flash.html.haml
- flash.each do |name, msg|
  :javascript
    Materialize.toast("#{msg}", 5000);

app/views/layouts/_footer.html.haml
%footer.page-footer
  .container
    .row.text-center
      .col.s12.m6
        %h4 Eden Design
        = link_to '208.713.0926', 'tel:+12087130926', class: 'margin-right'
        = link_to 'edenhibbert@gmail.com', 'mailto:edenhibbert@gmail.com'
      .col.s12.m6
        %h4.white-text Less is more.
        %p.text-mid — Ludwig Mies van der Rohe

  .footer-lower
    .container
      .row
        .col.s12.m4
          %span &copy; #{Time.now.year} EDEN
          = link_to 'COMFORT', sign_in_path, class: 'admin-link'
          %span HIBBERT
        .col.s12.m4.text-center
          .social-media
            = link_to 'http://www.pinterest.com/edenhibbert/', target: '_blank' do
              %span.fa.fa-pinterest
            = link_to 'http://www.linkedin.com/pub/eden-hibbert/7b/613/816/', target: '_blank' do
              %span.fa.fa-linkedin-square
            = link_to 'https://plus.google.com/u/0/100942330703858178433/about', target: '_blank' do
              %span.fa.fa-google-plus-square
        .col.s12.m4.text-right
          DESIGN & DEV
          = link_to '5TRINGY CREATIVE', 'http://stringycreative.com/', target: '_blank'

app/views/layouts/_nav.html.haml
%nav{:role => "navigation"}
  .nav-wrapper.container
    = link_to root_path, class: 'logo-container brand-logo' do
      %span Eden Design
      -# = image_tag('logo.svg', class: 'site-logo')
    %ul.right.hide-on-med-and-down
      = render 'layouts/nav_links'
    %ul#nav-mobile.side-nav
      = render 'layouts/nav_links'
    %a.button-collapse{"data-activates" => "nav-mobile", :href => "#"}
      %i.fa.fa-bars

app/views/layouts/_nav_links.html.haml
- nav_link('home', root_path)
- nav_link('work', work_path)
- nav_link('about', about_path)
- nav_link('contact', contact_path)
- if signed_in?
  %li.waves-effect.waves-nav{class: "#{'active' if params[:controller] == 'projects'}"}
    = link_to 'Projects', projects_path
  %li.waves-effect.waves-nav
    = link_to 'Sign Out', sign_out_path, method: :delete

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %title EdenPortfolio
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1.0", :name => "viewport"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    = render 'layouts/nav'

    %main
      #main-content.container
        .section
          = render 'layouts/flash'
          - if content_for?(:page_title)
            %h1= yield :page_title
        = yield
    - if params[:controller] == 'static'
      = render 'layouts/footer'
    - else
      .footer-padding

    = javascript_include_tag "salvattore"

app/views/projects/_form.html.haml
= form_for(@project) do |f|
  .row
    .input-field.col.s12.m6
      = f.text_field :name
      = f.label :name
    .input-field.col.s12.m6
      = f.date_field :date, class: 'datepicker'
      = f.label :date
    .input-field.col.s12
      = f.text_area :details, class: 'materialize-textarea'
      = f.label :details
  #images
  = f.fields_for :images do |image|
    = render 'projects/image_fields', f: image
  .links.col.s12
    = link_to_add_association f, :images, class: 'btn' do
      %span.fa.fa-plus
      %span Add Image

  .row
    .input-field.col.s12
      = f.submit nil, class: 'btn primary waves-effect waves-light'

app/views/projects/_image_fields.html.haml
.nested-fields.row
  .file-field.input-field.col.m6.s12
    .btn
      %span File
      = f.file_field :file
    .file-path-wrapper
      %input.file-path.validate{:type => "text"}/
  .col.m2.s6
    .margin-top
      = f.check_box :featured, checked: f.object.featured
      = f.label :featured
  .col.m2.s6
    .image-container
      = image_tag( f.object.file.url(:thumb), class: 'form-image' )
  .col.m2.s12.text-right
    = link_to_remove_association f, class: 'btn margin-top' do
      %span.fa.fa-trash

app/views/projects/edit.html.haml
= content_for(:page_title) do
  Edit Project

= render 'projects/form', project: @project

app/views/projects/index.html.haml
= content_for(:page_title) do
  Projects

%table.bordered.responsive-table
  %thead
    %tr
      %th{"data-field" => "name"} Name
      %th{"data-field" => "date"} Date
      %th{"data-field" => "details"} Details
      %th{"data-field" => "featured"} Featured
      %th{"data-field" => "actions"} Actions
  %tbody
    - @projects.each do |project|
      %tr
        %td= project.name
        %td= time_tag(project.date.to_date)
        %td= project.details
        %td
          %span.featured-icon{class: "#{ 'fa fa-star' if project.images.any? {|x| x.featured} }"}
        %td.project-actions
          = link_to edit_project_path(project.id), class: 'tooltipped', data: { position: "left", delay: "1", tooltip: "Edit" } do
            %i.fa.fa-pencil
          = link_to project_path(project.id), method: :delete, class: 'tooltipped', data: {confirm: "Are you sure you want to delete this project?", position: "right", delay: "1", tooltip: "Delete"} do
            %i.fa.fa-trash

.new-project
  = link_to new_project_path, class: 'btn primary waves-effect waves-light' do
    %i.fa.fa-plus
    %span New Project

app/views/projects/new.html.haml
= content_for(:page_title) do
  Create Project

= render 'projects/form', project: @project